apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
  - name: api
    image: yehudali/project_contacts:V1
    imagePullPolicy: Always



    ports:
    - containerPort: 8000
    env:
    - name: HOST
      value: "mongodb-service"
    - name: PORT
      value: "27017"
    - name: DB
      value: "contactsdb"
    - name: COLLECTION
      value: "contacts"